### ISSUE TITLE
Control Sidebar does not work

### ISSUE THREAD

**Issue by huysamen** [huxinghai1988/ember-adminlte-theme#1]
To reproduce:
- Create new Ember (2.6.0-beta.3) project
- Install ember-adminlte-theme plugin
- Add layout to application.hbs

The sidebar control does not work.

**Comment by huxinghai** [comment]
`application.hbs` layout what are the contents

**Comment by huysamen** [comment]
```
<div class="wrapper">
  {{main-header}}
  {{main-sidebar}}

  {{#content-wrapper}}
    {{outlet}}
  {{/content-wrapper}}

  {{main-footer}}
  {{control-sidebar}}
</div>
```

**Comment by huxinghai** [comment]
control sidebar should be able to work
